"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { database, ensureDatabase } from "@/lib/database";
import { appendPersistentAudit } from "@/lib/admin-data";
import { assertSameOrigin } from "@/lib/security/csrf";
import { sanitizeText } from "@/lib/security/text";
import type { MarketplaceActionState } from "./marketplace";

const state = (error: unknown): MarketplaceActionState => ({ ok: false, message: error instanceof Error ? error.message : "İşlem tamamlanamadı" });

async function prepareAdmin() { await assertSameOrigin(); await ensureDatabase(); return requireAdmin(); }

export async function userStatusAction(userId: string, status: "ACTIVE" | "SUSPENDED" | "BANNED"): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const id = z.string().uuid().parse(userId); if (id === admin.id) throw new Error("Kendi hesabınızın durumunu değiştiremezsiniz"); await database().prepare("UPDATE users SET status = ?, updated_at = ? WHERE id = ? AND role = 'USER'").bind(status, new Date().toISOString(), id).run(); await database().prepare("DELETE FROM sessions WHERE user_id = ? AND ? != 'ACTIVE'").bind(id, status).run(); await appendPersistentAudit({ actorId: admin.id, action: "USER_STATUS_UPDATED", targetType: "USER", targetId: id, newValue: { status } }); revalidatePath("/admin/users"); return { ok: true, message: "Kullanıcı durumu güncellendi" }; } catch (error) { return state(error); }
}

export async function productModerationAction(input: { productId: string; action: "APPROVE" | "REJECT" | "REMOVE"; note?: string }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const id = z.string().uuid().parse(input.productId); const status = input.action === "APPROVE" ? "ACTIVE" : input.action === "REJECT" ? "REJECTED" : "REMOVED"; await database().prepare("UPDATE products SET status = ?, rejection_reason = ?, updated_at = ? WHERE id = ?").bind(status, input.note ?? null, new Date().toISOString(), id).run(); await appendPersistentAudit({ actorId: admin.id, action: `PRODUCT_${input.action}`, targetType: "PRODUCT", targetId: id, newValue: { status, note: input.note } }); revalidatePath("/admin/products"); revalidatePath("/urunler"); return { ok: true, message: "İlan güncellendi" }; } catch (error) { return state(error); }
}

export async function requestVerificationAction(productId: string): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const id = z.string().uuid().parse(productId); const code = crypto.randomUUID().replaceAll("-", "").slice(0, 6).toUpperCase(); const now = new Date().toISOString(); const product = await database().prepare("SELECT id FROM products WHERE id = ?").bind(id).first(); if (!product) throw new Error("İlan bulunmuyor"); await database().prepare("INSERT INTO product_verifications (product_id,challenge_code,requested_at,status) VALUES (?,?,?,'REQUESTED') ON CONFLICT(product_id) DO UPDATE SET challenge_code=excluded.challenge_code,requested_at=excluded.requested_at,status='REQUESTED',submitted_at=NULL,evidence_image_key=NULL,reviewed_by=NULL,review_note=NULL").bind(id, code, now).run(); await appendPersistentAudit({ actorId: admin.id, action: "PRODUCT_VERIFICATION_REQUESTED", targetType: "PRODUCT", targetId: id, newValue: { code } }); revalidatePath("/admin/products"); return { ok: true, message: `Doğrulama kodu: ${code}` }; } catch (error) { return state(error); }
}
export async function reviewVerificationAction(input: { productId: string; verified: boolean; note: string }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const parsed = z.object({ productId: z.string().uuid(), verified: z.boolean(), note: z.string().max(1000) }).parse(input); const result = await database().prepare("UPDATE product_verifications SET status = ?, reviewed_by = ?, review_note = ? WHERE product_id = ? AND status = 'SUBMITTED'").bind(parsed.verified ? "VERIFIED" : "REJECTED", admin.id, sanitizeText(parsed.note, 1000), parsed.productId).run(); if (!result.meta.changes) throw new Error("İncelenecek kanıt bulunmuyor"); await appendPersistentAudit({ actorId: admin.id, action: parsed.verified ? "PRODUCT_VERIFIED" : "PRODUCT_VERIFICATION_REJECTED", targetType: "PRODUCT", targetId: parsed.productId, newValue: parsed }); return { ok: true, message: "Doğrulama kararı kaydedildi" }; } catch (error) { return state(error); }
}
export async function resolveDisputeAction(input: { disputeId: string; resolution: "REFUND" | "PARTIAL_REFUND" | "RELEASE"; amountKurus?: number; note: string }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const parsed = z.object({ disputeId: z.string().uuid(), resolution: z.enum(["REFUND", "PARTIAL_REFUND", "RELEASE"]), amountKurus: z.number().int().positive().optional(), note: z.string().min(3).max(2000) }).parse(input); const dispute = await database().prepare("SELECT d.order_id,o.product_price_kurus FROM disputes d JOIN orders o ON o.id = d.order_id WHERE d.id = ? AND d.status NOT IN ('CLOSED','RESOLVED_BUYER','RESOLVED_SELLER')").bind(parsed.disputeId).first<{ order_id: string; product_price_kurus: number }>(); if (!dispute) throw new Error("Uyuşmazlık bulunmuyor"); if (parsed.resolution === "PARTIAL_REFUND" && (!parsed.amountKurus || parsed.amountKurus >= dispute.product_price_kurus)) throw new Error("Kısmi iade tutarı geçersiz"); const buyerWins = parsed.resolution !== "RELEASE"; await database().batch([database().prepare("UPDATE disputes SET status = ? WHERE id = ?").bind(buyerWins ? "RESOLVED_BUYER" : "RESOLVED_SELLER", parsed.disputeId), database().prepare("UPDATE orders SET order_status = ?, payment_status = ? WHERE id = ?").bind(buyerWins ? "REFUNDED" : "COMPLETED", buyerWins ? (parsed.resolution === "PARTIAL_REFUND" ? "PARTIALLY_REFUNDED" : "REFUNDED") : "RELEASED", dispute.order_id)]); await appendPersistentAudit({ actorId: admin.id, action: `DISPUTE_${parsed.resolution}`, targetType: "DISPUTE", targetId: parsed.disputeId, newValue: parsed }); revalidatePath("/admin/disputes"); return { ok: true, message: "Uyuşmazlık kararı uygulandı" }; } catch (error) { return state(error); }
}
export async function publishLegalDocumentAction(input: { type: string; version: string; title: string; content: string }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const parsed = z.object({ type: z.enum(["USER_AGREEMENT","MARKETPLACE_AGREEMENT","SELLER_AGREEMENT","PRIVACY_NOTICE","KVKK_NOTICE","COOKIE_POLICY","DISTANCE_SALES_INFORMATION","DISTANCE_SALES_AGREEMENT_TEMPLATE","RETURN_REFUND_POLICY","PROHIBITED_PRODUCTS_POLICY","DISPUTE_POLICY","COMMISSION_POLICY"]), version: z.string().min(1).max(30), title: z.string().min(5).max(200), content: z.string().min(100).max(100000) }).parse(input); const id = crypto.randomUUID(); const now = new Date().toISOString(); await database().batch([database().prepare("UPDATE legal_documents SET active = 0 WHERE type = ?").bind(parsed.type), database().prepare("INSERT INTO legal_documents (id,type,version,title,content,active,published_at) VALUES (?,?,?,?,?,1,?)").bind(id, parsed.type, parsed.version, sanitizeText(parsed.title, 200), parsed.content, now)]); await appendPersistentAudit({ actorId: admin.id, action: "LEGAL_DOCUMENT_PUBLISHED", targetType: "LEGAL_DOCUMENT", targetId: id, newValue: { type: parsed.type, version: parsed.version } }); revalidatePath("/admin/legal"); return { ok: true, message: "Hukuki metin sürümü yayınlandı" }; } catch (error) { return state(error); }
}
export async function updateComplianceAction(input: { id: string; status: string; owner: string; note: string; evidenceUrl: string }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const parsed = z.object({ id: z.string().min(1).max(100), status: z.enum(["NOT_REVIEWED","IN_PROGRESS","READY","NEEDS_COUNSEL","BLOCKED"]), owner: z.string().max(120), note: z.string().max(2000), evidenceUrl: z.union([z.literal(""), z.string().url().max(1000)]) }).parse(input); const result = await database().prepare("UPDATE compliance_items SET status = ?, owner = ?, note = ?, evidence_url = ?, updated_at = ? WHERE id = ?").bind(parsed.status, sanitizeText(parsed.owner, 120) || null, sanitizeText(parsed.note, 2000) || null, parsed.evidenceUrl || null, new Date().toISOString(), parsed.id).run(); if (!result.meta.changes) throw new Error("Uyumluluk kaydı bulunmuyor"); await appendPersistentAudit({ actorId: admin.id, action: "COMPLIANCE_UPDATED", targetType: "COMPLIANCE", targetId: parsed.id, newValue: parsed }); revalidatePath("/admin/compliance"); return { ok: true, message: "Uyumluluk kaydı güncellendi" }; } catch (error) { return state(error); }
}
export async function markDeliveredAction(orderId: string): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const id = z.string().uuid().parse(orderId); const result = await database().prepare("UPDATE orders SET order_status = 'BUYER_CONFIRMATION_PENDING', shipping_status = 'DELIVERED' WHERE id = ? AND order_status IN ('SHIPPED','DELIVERED')").bind(id).run(); if (!result.meta.changes) throw new Error("Sipariş teslim edildi olarak işaretlenemiyor"); await appendPersistentAudit({ actorId: admin.id, action: "ORDER_MARKED_DELIVERED", targetType: "ORDER", targetId: id, newValue: { shippingStatus: "DELIVERED" } }); revalidatePath("/admin/orders"); return { ok: true, message: "Teslimat kaydedildi; satıcı ödemesi alıcı onayını bekliyor" }; } catch (error) { return state(error); }
}
export async function requestDisputeEvidenceAction(disputeId: string, party: "BUYER" | "SELLER"): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const id = z.string().uuid().parse(disputeId); const result = await database().prepare("UPDATE disputes SET status = ? WHERE id = ? AND status NOT IN ('CLOSED','RESOLVED_BUYER','RESOLVED_SELLER')").bind(party === "BUYER" ? "WAITING_BUYER" : "WAITING_SELLER", id).run(); if (!result.meta.changes) throw new Error("Uyuşmazlık bulunmuyor"); await appendPersistentAudit({ actorId: admin.id, action: "DISPUTE_EVIDENCE_REQUESTED", targetType: "DISPUTE", targetId: id, newValue: { party } }); revalidatePath("/admin/disputes"); return { ok: true, message: "Kanıt talebi kaydedildi" }; } catch (error) { return state(error); }
}

export async function updateSettingsAction(input: { commissionType: "PERCENTAGE" | "FIXED" | "HYBRID"; percentageBasisPoints: number; fixedFeeKurus: number; minimumFeeKurus: number; maximumFeeKurus: number | null; maintenanceMode: boolean; disputePeriodHours: number; sellerShippingDeadlineHours: number; buyerConfirmationPeriodHours: number; prohibitedCategories: string[] }): Promise<MarketplaceActionState> {
  try { const admin = await prepareAdmin(); const parsed = z.object({ commissionType: z.enum(["PERCENTAGE", "FIXED", "HYBRID"]), percentageBasisPoints: z.number().int().min(0).max(10000), fixedFeeKurus: z.number().int().min(0), minimumFeeKurus: z.number().int().min(0), maximumFeeKurus: z.number().int().min(0).nullable(), maintenanceMode: z.boolean() }).parse(input); await database().prepare("UPDATE platform_settings SET commission_type = ?, percentage_basis_points = ?, fixed_fee_kurus = ?, minimum_fee_kurus = ?, maximum_fee_kurus = ?, maintenance_mode = ?, updated_at = ? WHERE id = 1").bind(parsed.commissionType, parsed.percentageBasisPoints, parsed.fixedFeeKurus, parsed.minimumFeeKurus, parsed.maximumFeeKurus, parsed.maintenanceMode ? 1 : 0, new Date().toISOString()).run(); await appendPersistentAudit({ actorId: admin.id, action: "SETTINGS_UPDATED", targetType: "PLATFORM_SETTINGS", targetId: "1", newValue: parsed }); revalidatePath("/admin/settings"); return { ok: true, message: "Ayarlar güncellendi" }; } catch (error) { return state(error); }
}
