import Link from "next/link";
import { ProductCard } from "@/components/product-card";
import { demoCategories, demoProducts } from "@/lib/demo";
import { listPersistentProducts } from "@/lib/persistent-marketplace";

export const dynamic = "force-dynamic";
export default async function HomePage() {
  const storedProducts = await listPersistentProducts().catch(() => []);
  const featuredProducts = storedProducts.length ? storedProducts.slice(0, 4) : demoProducts.slice(0, 4);
  return <>
    <section className="market-hero"><div className="hero-content"><span className="kicker">TÜRKİYE'NİN GÜVENLİ C2C PAZARI</span><h1>Gerçek insanlar.<br/><em>Güvenli alışveriş.</em></h1><p>Sevdiğin ürünleri keşfet, kullanmadıklarını değerlendir. Ödeme ve teslimat adımları şeffaf, tarafların hakları koruma altında.</p><div><Link href="/urunler" className="button primary">Ürünleri keşfet <span>→</span></Link><Link href="/sat" className="button ghost">Ücretsiz ilan ver</Link></div><ul><li>✓ Satıcı doğrulama</li><li>✓ Teslimat onayı</li><li>✓ Uyuşmazlık desteği</li></ul></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1400&q=88" alt="Güvenli alışveriş için hazırlanmış paketler"/><div className="protection-card"><i>✓</i><div><b>Alıcı koruması</b><small>Satıcı ödemesi yalnızca güvenli release koşullarıyla başlatılır</small></div></div></div></section>
    <div className="dev-payment-banner">Demo ödeme modu aktiftir. Lisanslı ödeme kuruluşu entegrasyonu tamamlanana kadar gerçek para hareketi yapılmaz.</div>
    <section className="trust-strip"><div><b>Güvenli ödeme</b><small>Lisanslı provider mimarisine hazır</small></div><div><b>Doğrulanmış ilan</b><small>Kanıt fotoğrafı akışı</small></div><div><b>Şeffaf takip</b><small>Sipariş ve kargo zaman çizelgesi</small></div><div><b>İnsan desteği</b><small>Uyuşmazlık inceleme süreci</small></div></section>
    <section className="content-section"><div className="section-title"><div><span className="kicker dark">KATEGORİLER</span><h2>Aradığını kolayca bul</h2></div><Link href="/urunler">Tümünü gör →</Link></div><div className="category-list">{demoCategories.map((category, index) => <Link prefetch={false} key={category.slug} href={`/urunler?kategori=${category.slug}`}><i>{["⌁","⌂","◇","◉","✦","○"][index]}</i><b>{category.name}</b><span>Keşfet →</span></Link>)}</div></section>
    <section className="content-section products-section"><div className="section-title"><div><span className="kicker dark">ÖNE ÇIKANLAR</span><h2>Topluluğun favorileri</h2></div><Link href="/urunler">Tüm ilanlar →</Link></div><div className="market-grid">{featuredProducts.map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>
    <section className="how-section"><div className="section-title centered"><div><span className="kicker">NASIL ÇALIŞIR?</span><h2>Üç adımda güvenli alışveriş</h2></div></div><div className="steps"><article><i>1</i><b>Ürünü keşfet</b><p>İlanı, satıcı puanını ve doğrulama durumunu incele.</p></article><article><i>2</i><b>Güvenle satın al</b><p>Ödeme işlemi lisanslı sağlayıcı entegrasyonuna hazır korumalı akışta ilerler.</p></article><article><i>3</i><b>Teslim al ve onayla</b><p>Ürünü kontrol et. Sorun varsa süre içinde uyuşmazlık aç.</p></article></div></section>
    <section className="safety-section"><div><span className="kicker dark">ORTAKPAZAR KORUMASI</span><h2>Her adımda<br/>kontrol sende.</h2><p>Kargoya verildi bilgisi tek başına satıcıya ödeme yapılması için yeterli değildir. Teslimat, alıcı onayı ve uyuşmazlık durumu birlikte değerlendirilir.</p><Link href="/guvenli-alisveris" className="text-link">Koruma sistemini incele →</Link></div><div className="safety-grid"><article><i>⌁</i><b>Provider tabanlı ödeme</b><p>Kart verisi platform veritabanında tutulmaz.</p></article><article><i>✓</i><b>İlan doğrulama</b><p>Rastgele kodlu kanıt fotoğrafı istenebilir.</p></article><article><i>↺</i><b>Uyuşmazlık çözümü</b><p>Dispute açıkken satıcı ödemesi bloke edilir.</p></article><article><i>◎</i><b>Değerlendirme</b><p>Tamamlanan işlem sonrası karşılıklı puanlama.</p></article></div></section>
    <section className="sell-cta"><div><span className="kicker">DAHA AZ İSRAF, DAHA ÇOK DEĞER</span><h2>Kullanmadığın ürünler<br/>yeni sahibini bulsun.</h2></div><Link href="/sat" className="button lime">İlan vermeye başla →</Link></section>
  </>;
}
