import { OrderActions } from "@/components/account-actions";
import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { formatMoney } from "@/lib/demo";
import { listPersistentOrders } from "@/lib/persistent-orders";

export const dynamic = "force-dynamic";
const labels: Record<string, string> = { SELLER_PREPARING: "Satıcı hazırlıyor", SHIPPED: "Kargoda", DELIVERED: "Teslim edildi", BUYER_CONFIRMATION_PENDING: "Alıcı onayı bekleniyor", COMPLETED: "Tamamlandı", DISPUTED: "Uyuşmazlık açık", REFUNDED: "İade edildi", CANCELLED: "İptal edildi" };
export default async function OrdersPage() { const user = await requireUser("/siparisler"); const orders = await listPersistentOrders(user.id); return <div className="dashboard-page"><div className="page-heading"><span className="kicker dark">İŞLEM GEÇMİŞİ</span><h1>Siparişlerim</h1><p>Alış ve satış işlemlerinin tüm adımlarını buradan takip et.</p></div><div className="order-list">{orders.map((order) => { const mode = order.buyer_id === user.id ? "BUYER" as const : "SELLER" as const; const otherId = mode === "BUYER" ? order.seller_id : order.buyer_id; return <article key={order.id}><div><span className={`status ${order.order_status.toLowerCase()}`}>{labels[order.order_status] ?? order.order_status}</span><small>{mode === "BUYER" ? "Satın alma" : "Satış"} · {new Date(order.created_at).toLocaleDateString("tr-TR")}</small></div><h2>{order.product_title}</h2><div className="order-meta"><span>Ürün bedeli <b>{formatMoney(order.product_price_kurus)}</b></span>{mode === "SELLER" && <span>Satıcı net <b>{formatMoney(order.seller_net_amount_kurus)}</b></span>}<span>Ödeme <b>{order.payment_status}</b></span><span>Kargo <b>{order.shipping_status}</b></span></div><div className="order-actions"><Link href={`/mesajlar?user=${otherId}&order=${order.id}`}>Mesaj gönder</Link></div><OrderActions orderId={order.id} mode={mode} status={order.order_status}/></article>; })}{orders.length === 0 && <div className="empty-state"><h2>Henüz sipariş yok</h2><p>Alış veya satış işlemleriniz burada görünecek.</p></div>}</div></div>; }
