import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { database, ensureDatabase } from "@/lib/database";

export const dynamic = "force-dynamic";
const slugTypes: Record<string, string> = { "kullanici-sozlesmesi": "USER_AGREEMENT", "pazaryeri-sozlesmesi": "MARKETPLACE_AGREEMENT", "satici-sozlesmesi": "SELLER_AGREEMENT", "gizlilik-bildirimi": "PRIVACY_NOTICE", "kvkk-aydinlatma": "KVKK_NOTICE", "cerez-politikasi": "COOKIE_POLICY", "mesafeli-satis": "DISTANCE_SALES_INFORMATION", "iade-politikasi": "RETURN_REFUND_POLICY", "yasakli-urunler": "PROHIBITED_PRODUCTS_POLICY", "uyusmazlik-politikasi": "DISPUTE_POLICY", "komisyon-politikasi": "COMMISSION_POLICY" };
interface DocumentRow { title: string; version: string; content: string; published_at: string }
async function loadDocument(slug: string): Promise<DocumentRow | null> { const type = slugTypes[slug]; if (!type) return null; await ensureDatabase(); return database().prepare("SELECT title,version,content,published_at FROM legal_documents WHERE type = ? AND active = 1 ORDER BY published_at DESC LIMIT 1").bind(type).first<DocumentRow>(); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const document = await loadDocument(slug); return { title: document?.title ?? "Hukuki metin", description: document ? `${document.title} sürüm ${document.version}` : "OrtakPazar hukuki metni" }; }
export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const document = await loadDocument(slug); if (!document) notFound(); return <article className="legal-page"><span className="kicker dark">HUKUKİ METİN</span><h1>{document.title}</h1><div className="legal-meta">Sürüm {document.version} · {new Date(document.published_at).toLocaleDateString("tr-TR")}</div><div className="legal-warning">Bu metin production öncesinde yetkin bir hukuk danışmanı tarafından doğrulanmalıdır. Kesin hukuki uygunluk beyanı değildir.</div><div className="legal-content">{document.content}</div></article>; }
