import { notFound } from "next/navigation";
import { DisputeAdminActions, LegalPublishForm, OrderAdminActions, ProductAdminActions, SettingsForm, UserAdminActions } from "@/components/admin-controls";
import { requireAdmin } from "@/lib/auth";
import { formatMoney } from "@/lib/demo";
import { getDashboardMetrics } from "@/lib/marketplace/admin";
import { createSupabaseAdminClient } from "@/lib/supabase/server";

const allowed = new Set(["users", "products", "orders", "disputes", "finance", "settings", "legal", "audit"]);
export default async function AdminSectionPage({ params }: { params: Promise<{ section: string }> }) { const { section } = await params; if (!allowed.has(section)) notFound(); const admin = await requireAdmin(); const client = createSupabaseAdminClient();
  if (section === "users") { const { data } = await client.from("users").select("id,email,role,status,created_at,profiles(first_name,last_name,identity_verification_status)").order("created_at", { ascending: false }).limit(100); return <AdminTable title="Kullanıcılar" headers={["Kullanıcı", "Rol", "Durum", "Kayıt", "Aksiyon"]}>{data?.map((user) => <tr key={user.id}><td><b>{user.email}</b><small>{user.profiles?.[0] ? `${user.profiles[0].first_name} ${user.profiles[0].last_name}` : "Profil yok"}</small></td><td>{user.role}</td><td>{user.status}</td><td>{new Date(user.created_at).toLocaleDateString("tr-TR")}</td><td><UserAdminActions userId={user.id}/></td></tr>)}</AdminTable>; }
  if (section === "products") { const { data } = await client.from("products").select("id,title,status,price_kurus,location,created_at,seller:users(email),verification:product_verifications(status,challenge_code)").order("created_at", { ascending: false }).limit(100); return <AdminTable title="İlanlar" headers={["İlan", "Fiyat", "Durum", "Satıcı", "Aksiyon"]}>{data?.map((product) => <tr key={product.id}><td><b>{product.title}</b><small>{product.location}</small></td><td>{formatMoney(product.price_kurus)}</td><td>{product.status}</td><td>{product.seller?.[0]?.email ?? "—"}</td><td><ProductAdminActions productId={product.id}/></td></tr>)}</AdminTable>; }
  if (section === "orders") { const { data } = await client.from("orders").select("id,product_title,product_price_kurus,order_status,payment_status,shipping_status,created_at").order("created_at", { ascending: false }).limit(100); return <AdminTable title="Siparişler" headers={["Sipariş", "Tutar", "Durum", "Ödeme/Kargo", "Aksiyon"]}>{data?.map((order) => <tr key={order.id}><td><b>{order.product_title}</b><small>{order.id}</small></td><td>{formatMoney(order.product_price_kurus)}</td><td>{order.order_status}</td><td>{order.payment_status}<small>{order.shipping_status}</small></td><td><OrderAdminActions orderId={order.id} canMarkDelivered={order.order_status === "SHIPPED"}/></td></tr>)}</AdminTable>; }
  if (section === "disputes") { const { data } = await client.from("disputes").select("id,reason,description,status,created_at,order_id,evidence:dispute_evidence(storage_path,description)").order("created_at", { ascending: false }).limit(100); const paths = (data ?? []).flatMap((dispute) => dispute.evidence.map((item) => item.storage_path)); const { data: signed } = paths.length ? await client.storage.from("private-evidence").createSignedUrls(paths, 600) : { data: [] }; const urls = new Map((signed ?? []).flatMap((item) => item.signedUrl ? [[item.path, item.signedUrl] as const] : [])); return <AdminTable title="Uyuşmazlıklar" headers={["Neden", "Açıklama/Delil", "Durum", "Sipariş", "Aksiyon"]}>{data?.map((dispute) => <tr key={dispute.id}><td><b>{dispute.reason}</b><small>{new Date(dispute.created_at).toLocaleDateString("tr-TR")}</small></td><td>{dispute.description}{dispute.evidence.map((item) => { const url = urls.get(item.storage_path); return url ? <a key={item.storage_path} href={url} target="_blank" rel="noreferrer">Delili görüntüle</a> : null; })}</td><td>{dispute.status}</td><td>{dispute.order_id}</td><td><DisputeAdminActions disputeId={dispute.id}/></td></tr>)}</AdminTable>; }
  if (section === "finance") { const metrics = await getDashboardMetrics(admin); return <><div className="admin-heading"><h1>Finans</h1><p>Para değerleri kuruş tabanlı server-side kayıtlardan hesaplanır.</p></div><div className="metric-grid"><article><small>Gross transaction volume</small><b>{formatMoney(metrics.volumeKurus)}</b></article><article><small>Platform komisyonu</small><b>{formatMoney(metrics.revenueKurus)}</b></article><article><small>Satıcıya ödenecek</small><b>{formatMoney(metrics.sellerPayableKurus)}</b></article><article><small>Ödenen satıcı tutarı</small><b>{formatMoney(metrics.paidSellerKurus)}</b></article><article><small>Bekleyen fon</small><b>{formatMoney(metrics.pendingPayoutKurus)}</b></article><article><small>Refund</small><b>{metrics.refunds}</b></article></div></>; }
  if (section === "settings") { const { data } = await client.from("platform_settings").select("*").eq("id", 1).single(); if (!data) return <p>Ayarlar bulunamadı.</p>; return <><div className="admin-heading"><h1>Platform ayarları</h1><p>Komisyon değerleri sipariş oluşturulurken snapshot olarak saklanır.</p></div><SettingsForm settings={data}/></>; }
  if (section === "legal") { const { data } = await client.from("legal_documents").select("id,type,version,title,active,published_at,requires_legal_review").order("created_at", { ascending: false }); return <><div className="admin-heading"><h1>Hukuki metinler</h1><p>Metinler versiyonlu saklanır; eski siparişlerin kabul ettiği sürüm korunur.</p></div><LegalPublishForm/><div className="admin-list">{data?.map((document) => <article key={document.id}><b>{document.title}</b><span>{document.type} · v{document.version} · {document.active ? "Aktif" : "Arşiv"}</span></article>)}</div></>; }
  const { data } = await client.from("audit_logs").select("id,actor_id,action,target_type,target_id,ip_address,user_agent,timestamp,entry_hash").order("timestamp", { ascending: false }).limit(200); return <AdminTable title="Değiştirilemez audit kayıtları" headers={["Aksiyon", "Hedef", "Aktör", "Zaman", "Hash"]}>{data?.map((log) => <tr key={log.id}><td><b>{log.action}</b></td><td>{log.target_type}<small>{log.target_id}</small></td><td>{log.actor_id ?? "Sistem"}</td><td>{new Date(log.timestamp).toLocaleString("tr-TR")}</td><td>{log.entry_hash.slice(0, 12)}…</td></tr>)}</AdminTable>;
}

function AdminTable({ title, headers, children }: { title: string; headers: string[]; children: React.ReactNode }) { return <><div className="admin-heading"><h1>{title}</h1></div><div className="admin-table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div></>; }
